
name: LOTR_CI


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: |
            mkdir lib
            git clone https://github.com/google/googletest.git lib/
            mkdir build && cd build
            cmake -DCMAKE_INSTALL_PREFIX=executable_files .. && make && make install


    - name: Run prog & tests
      run: |
            cd build/executable_files
            ./LOTR_tests